version: 3

vars:
  SRC_DIR: src
  SRC_FILES:
    sh: ls -A "{{.SRC_DIR}}"
  SOURCE_FILES: |-
    wombat.lua
    {{ range $each_index, $each_file := .SRC_FILES | splitLines -}}
    src/{{ $each_file }}
    {{ end }}

tasks:
  print:
    cmds:
      - cmd: printf "{{.SOURCE_FILES}}" >> "{{.ADDON_MANIFEST_PATH}}"
        silent: true
