version: 3

vars:
  ADDON_MANIFEST_PATH_RAW: "{{.ADDON_DIRECTORY}}/{{.ADDON_NAME}}.txt"
  ADDON_MANIFEST_PATH: "{{fromSlash .ADDON_MANIFEST_PATH_RAW}}"
  TEMPLATE: |
    ## Title: {{.ADDON_NAME}}
    ## APIVersion: {{.API_VERSION}}
    ## Author: {{.AUTHOR}}
    ## Description: {{.DESCRIPTION}}\n

includes:
  register:
    taskfile: "register.yaml"
    internal: true
  src:
    taskfile: "source_files.yaml"
    internal: true
  ui:
    taskfile: "ui_files.yaml"
    internal: true
  custom:
    taskfile: "custom_resources.yaml"
    internal: true

tasks:
  default:
    desc: Generate the add manifest
    cmds:
      - task: register

      - cmd: echo Generating addon manifest at "{{.ADDON_MANIFEST_PATH}}"
        silent: true
      - cmd: printf "{{.TEMPLATE}}" > "{{.ADDON_MANIFEST_PATH}}"
        silent: true

      - task: register:add-source-to-manifest
      - task: src
      - task: ui
      - task: custom
