version: 3

vars:
  ADDON_MANIFEST_PATH_RAW: "{{.ADDON_DIRECTORY}}/{{.ADDON_NAME}}.txt"
  ADDON_MANIFEST_PATH: "{{fromSlash .ADDON_MANIFEST_PATH_RAW}}"
  TEMPLATE: |
    ## Title: {{.ADDON_NAME}}
    ## APIVersion: {{.API_VERSION}}
    ## Author: {{.AUTHOR}}
    ## Description: {{.DESCRIPTION}}\n

includes:
  src:
    taskfile: "source_files.yaml"
    internal: true
  ui:
    taskfile: "ui_files.yaml"
    internal: true
  custom:
    taskfile: "custom_resources.yaml"
    internal: true

tasks:
  print:
    internal: true
    cmds:
      - cmd: printf "{{.TEMPLATE}}" > "{{.ADDON_MANIFEST_PATH}}"
        silent: true

  template:
    desc: Generate the AddOn txt manifest
    cmds:
      - cmd: echo Generating addon manifest at "{{.ADDON_MANIFEST_PATH}}"
        silent: true
      - task: print
      - task: src:print
      - task: ui:print
      - task: custom:print
